development:
  adapter: postgresql
  encoding: utf8
  database: posts_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: posts_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: posts_db
  pool: 5
  username:
  password: