# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24be1829f55bbf12143bd688d1dc7b454df17f7e73be7e96f0ff7233e3243a83726533c28f5322826c6239897b678f012bb697a9872e58a392ade5096c518234

test:
  secret_key_base: d5ca9b0053f355283df78eecc4e59d6d1816efd15cef878b5850f953b81805827a8e3ba448458f4403c5bdbbfbea72f6aa37cb1013360eef2c6e16995ed5ccd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
